export declare type KOREAN = 'ko';
export declare type ENGLISH = 'en';
export declare type JAPANESE = 'ja';
export declare type CHINESE_SIMPLIFIED = 'zh-CN';
export declare type CHINESE_TRADITIONAL = 'zh-TW';
export declare type SPANISH = 'es';
export declare type FRENCH = 'fr';
export declare type GERMAN = 'de';
export declare type RUSSIAN = 'ru';
export declare type PORTUGUESE = 'pt';
export declare type ITALIAN = 'it';
export declare type VIETNAMESE = 'vi';
export declare type THAI = 'th';
export declare type INDONESIAN = 'id';
export declare type HINDI = 'hi';
export declare type LANGUAGE = KOREAN | ENGLISH | JAPANESE | CHINESE_SIMPLIFIED | CHINESE_TRADITIONAL | SPANISH | FRENCH | GERMAN | RUSSIAN | PORTUGUESE | ITALIAN | VIETNAMESE | THAI | INDONESIAN | HINDI;
export declare const languages: {
    ko: string;
    en: string;
    ja: string;
    'zh-CN': string;
    'zh-TW': string;
    es: string;
    fr: string;
    de: string;
    ru: string;
    pt: string;
    it: string;
    vi: string;
    th: string;
    id: string;
    hi: string;
};
